name: docker_login

on:
  label:
    types:
      - created

jobs:        
  docker_login:
    runs-on: [self-hosted, linux, x64]
    steps:
      # No changes

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
  docker_push:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sdcproject1/imagev1:latest

      # - name: Build and push
      #   run: |
      #     sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api_image1:v1 .
      #     sudo docker tag ${{ secrets.DOCKERHUB_USERNAME }}/api_image1:v1 ${{ secrets.DOCKERHUB_USERNAME }}/version1:v1
      #     sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/version1:v1
