name: docker_login

on:
  label:
    types:
      - created

jobs:        
  docker_login:
    runs-on: [self-hosted, linux, x64]
    steps:
      # No changes

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
  docker_push:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Build and push
        run: |
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api_image1:v1 .
