name: docker_login

on:
  label:
    types:
      - created

jobs:        
  docker_login:
    runs-on: [self-hosted, linux, x64]
    steps:
      # No changes

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sdcproject1/my-image:latest
 
  docker_push:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build and push
        run: |
          sudo docker run -d -p 8001:80 sdcproject1/my-image --name container1

#sudo docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password ${{ secrets.DOCKERHUB_TOKEN }}
