name: Build and Test

on:
  label:
    types:
      - created

jobs:
  test:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Run application 
      run: |
        echo "hi"
        
  docker_login:
    runs-on: [self-hosted, linux, x64]
    steps:
      # No changes

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: akoskm/my-image:latest
